### ISSUE TITLE
Random number generation

### ISSUE THREAD

**Issue by harikt** [paragonie/awesome-appsec#1]
I think https://github.com/ircmaxell/RandomLib library serves the needs than using urandom.

**Comment by technion** [comment]
Given it's a PHP library it's not useful to any other developer.

Why would you recommend a third party library in place of an incredibly well vetted OS feature?

**Comment by harikt** [comment]
> Given it's a PHP library it's not useful to any other developer.

Ya, may not be good other than PHP developers.

> Why would you recommend a third party library in place of an incredibly well vetted OS feature?

@technion Funny that you can recommend the blog. https://github.com/paragonie/awesome-appsec#ircmaxells-blog but not code.

**Comment by technion** [comment]
Do you have an actual problem with /dev/urandom or are you just pushing a library?

**Comment by harikt** [comment]
> Do you have an actual problem with /dev/urandom 

No. I have not used.

> or are you just pushing a library?

I was to here from  http://www.reddit.com/r/PHP/comments/34gv1i/a_curated_list_for_learning_about_application/ . ie a PHP related one I believe. So I thought if someone needs they can use the library too.

Hope that helps. Do you think the library is not strong enough to create random number ?

Thank you

**Comment by paragonie-scott** [comment]
Closed by https://github.com/paragonie/awesome-appsec/commit/16ca455a435cc625b07cf699aabdd362b5e92a3b
