### ISSUE TITLE
C Reading List?

### ISSUE THREAD

**Issue by paragonie-scott** [paragonie/awesome-appsec#10]

**Comment by alanc** [comment]
* [CERT C Coding Standard](https://www.securecoding.cert.org/confluence/display/c/SEI+CERT+C+Coding+Standard)
* [Secure Programming for Linux and Unix HOWTO — Creating Secure Software](http://www.dwheeler.com/secure-programs/Secure-Programs-HOWTO/index.html)
* [Defensive Coding: A Guide to Improving Software Security by the Fedora Security Team](https://docs.fedoraproject.org/en-US/Fedora_Security_Team/1/html/Defensive_Coding/index.html)

**Comment by 4chm3d** [comment]
Hi @alanc, I just changed the date [here](https://github.com/paragonie/awesome-appsec/blob/master/data/C/books-and-ebooks/0002-fedora-defensive-coding.json#L2) because of #52.
