### ISSUE TITLE
Add Web application security quiz to the list

### ISSUE THREAD

**Issue by timoh6** [paragonie/awesome-appsec#2]
I have been maintaining a small web application specific quiz at http://timoh6.github.io/WebAppSecQuiz/ (tests knowledge about different kind of quirks and so on regarding to web application security).

Maybe this could be used on the list? Under "General"?

**Comment by paragonie-scott** [comment]
:+1: Closed by https://github.com/paragonie/awesome-appsec/commit/16ca455a435cc625b07cf699aabdd362b5e92a3b
