### ISSUE TITLE
Node.js Reading List?

### ISSUE THREAD

**Issue by paragonie-scott** [paragonie/awesome-appsec#3]
Are there any great articles, books, blogs, etc. for writing secure Node.js software? If so, let us know and we'll add them to the list.

**Comment by FranckKe** [comment]
A blog article came out not so long ago

https://blog.risingstack.com/node-js-security-checklist/

**Comment by paragonie-scott** [comment]
Thanks for the recommendation. This is definitely valuable information worth sharing.

The only thing I dislike or would be concerned about is that the way the article is written fosters a [checklist mentality](blogs.technet.com/b/johnla/archive/2015/04/26/defenders-think-in-lists-attackers-think-in-graphs-as-long-as-this-is-true-attackers-win.aspx), which leads to ineffective defenders.

**Comment by FranckKe** [comment]
Indeed, did you consider add a disclaimer/note about that matter?

**Comment by paragonie-scott** [comment]
I actually left a comment on the article itself, in case linking to it made it more popular and/or rank higher and people found the article without going through this list.

**Comment by FranckKe** [comment]
:+1:

**Comment by timkuijsten** [comment]
I liked http://blog.websecurify.com/2014/08/hacking-nodejs-and-mongodb.html.
