### ISSUE TITLE
Suggested links to add

### ISSUE THREAD

**Issue by abderraouf-adjal** [paragonie/awesome-appsec#4]
https://crackstation.net/hashing-security.htm
http://insanecoding.blogspot.co.uk/2014/05/a-good-idea-with-bad-usage-devurandom.html
http://www.cyberciti.biz/tips/php-security-best-practices-tutorial.html
http://blog.astrumfutura.com/2013/04/20-point-list-for-preventing-cross-site-scripting-in-php
https://timoh6.github.io/2014/06/16/PHP-data-encryption-cheatsheet.html
https://timoh6.github.io/WebAppSecQuiz/index.html
http://lzone.de/cheat-sheet/Security-News-Feeds

**Comment by paragonie-scott** [comment]
Thank you very much!  :+1: 

I added the first two on your list, I'll review the rest of them as soon as possible.
