### ISSUE TITLE
Python Reading List?

### ISSUE THREAD

**Issue by paragonie-scott** [paragonie/awesome-appsec#8]
Are there any recommended Python books, articles, blogs, etc.?

**Comment by alanc** [comment]
* [OWASP Python Security wiki](https://github.com/ebranca/owasp-pysec/wiki)
* [Python chapter of Fedora Defensive Coding Guide](https://docs.fedoraproject.org/en-US/Fedora_Security_Team/1/html/Defensive_Coding/chap-Defensive_Coding-Python.html)
