### ISSUE TITLE
 CERT Coding Standard

### ISSUE THREAD

**Issue by abderraouf-adjal** [paragonie/awesome-appsec#9]
CERT C Coding Standard: https://www.securecoding.cert.org/confluence/display/c/CERT+C+Coding+Standard

 CERT C++ Coding Standard: https://www.securecoding.cert.org/confluence/pages/viewpage.action?pageId=637

Android, Java, Perl: https://www.securecoding.cert.org/confluence/spacedirectory/view.action

**Comment by paragonie-scott** [comment]
:+1: Excellent! Thank you for sharing this.

We're going to reach out to experts in those languages soon and see if we can give them the coverage they deserve.
